
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons?name_like=Ada

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "John Doe",
    "number": "09322926010"
}